ASPNETCore-Parte5-master/antes/Item04/CasaDoCodigo/Areas/Catalogo/Models/ViewModels/CarrosselPaginaViewModel.cs
using CasaDoCodigo.Models;
using System.Collections.Generic;

namespace CasaDoCodigo.Areas.Catalogo.Models.ViewModels
{
    public class CarrosselPaginaViewModel
    {
        public CarrosselPaginaViewModel(IList<Produto> produtos, int indice)
        {
            Produtos = produtos;
            Indice = indice;
        }

        public IList<Produto> Produtos { get; set; }
        public int Indice { get; set; }
    }
}

ASPNETCore-Parte5-master/antes/Item04/CasaDoCodigo/Areas/Catalogo/ViewComponents/ProdutoCardViewComponent.cs
using CasaDoCodigo.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CasaDoCodigo.Areas.Catalogo.ViewComponents
{
    public class ProdutoCardViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(Produto produto)
        {
            return View("Default", produto);
        }
    }
}

ASPNETCore-Parte5-master/antes/Item04/CasaDoCodigo/Areas/Catalogo/Views/Home/Components/CarrosselPagina/Default.cshtml
@addTagHelper *, CasaDoCodigo.MVC
@using CasaDoCodigo.Areas.Catalogo.Models.ViewModels
@model CarrosselPaginaViewModel

<div class="item @(Model.Indice == 0 ? "active" : "")">
    <div class="row">
        @foreach (var produto in Model.Produtos)
        {
            <vc:produto-card produto="@produto"/>
        }
    </div>
</div>