ASPNETCore-Parte5-master/depois/Item03/CasaDoCodigo/Areas/Catalogo/Models/ViewModels/CarrosselViewModel.cs
using CasaDoCodigo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CasaDoCodigo.Areas.Catalogo.Models.ViewModels
{
    public class CarrosselViewModel
    {
        public CarrosselViewModel(Categoria categoria, IList<Produto> produtos, int numPaginas, int tamanhoPagina)
        {
            Categoria = categoria;
            Produtos = produtos;
            NumPaginas = numPaginas;
            TamanhoPagina = tamanhoPagina;
        }

        public Categoria Categoria { get; set; }
        public IList<Produto> Produtos { get; set; }
        public int NumPaginas { get; set; }
        public int TamanhoPagina { get; set; }
    }
}

ASPNETCore-Parte5-master/depois/Item03/CasaDoCodigo/Areas/Catalogo/ViewComponents/CarrosselPaginaViewComponent.cs
using CasaDoCodigo.Areas.Catalogo.Models.ViewModels;
using CasaDoCodigo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace CasaDoCodigo.Areas.Catalogo.ViewComponents
{
    public class CarrosselPaginaViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IList<Produto> produtosNaCategoria, int indicePagina, int tamanhoPagina)
        {
            var produtosNaPagina =
                produtosNaCategoria
                .Skip(indicePagina * tamanhoPagina)
                .Take(tamanhoPagina)
                .ToList();

            return View("Default",
                new CarrosselPaginaViewModel(produtosNaPagina, indicePagina));
        }
    }
}

ASPNETCore-Parte5-master/depois/Item03/CasaDoCodigo/Areas/Catalogo/ViewComponents/CarrosselViewComponent.cs
using CasaDoCodigo.Areas.Catalogo.Models.ViewModels;
using CasaDoCodigo.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CasaDoCodigo.Areas.Catalogo.ViewComponents
{
    public class CarrosselViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(Categoria categoria, IList<Produto> produtos, int tamanhoPagina)
        {
            var produtosNaCategoria =
                produtos
                .Where(p => p.Categoria.Id == categoria.Id)
                .ToList();

            int paginas = (int)Math.Ceiling((double)produtosNaCategoria.Count() / tamanhoPagina);

            return View("Default",
                new CarrosselViewModel(categoria, produtosNaCategoria, paginas, tamanhoPagina));
        }
    }
}

ASPNETCore-Parte5-master/depois/Item03/CasaDoCodigo/Areas/Catalogo/Views/Home/Components/Carrossel/Default.cshtml
@addTagHelper *, CasaDoCodigo.MVC
@using CasaDoCodigo.Areas.Catalogo.Models.ViewModels
@model CarrosselViewModel
@{ 
    var categoria = Model.Categoria;
}

<h3>@categoria.Nome</h3>

<div id="my-carousel-@categoria.Id" class="carousel slide" data-ride="carousel">
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        @for (int pagina = 0; pagina < Model.NumPaginas; pagina++)
        {
            <vc:carrossel-pagina indice-pagina="@pagina" produtos-na-categoria="@Model.Produtos" tamanho-pagina="@Model.TamanhoPagina"/>
        }
    </div>
    <!-- Controls -->
    <partial name="_NavegacaoCarrossel" model="@categoria" />
</div>